name: Java Spring Boot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Package Spring Boot application
      run: mvn package -DskipTests=true

    - name: Display test coverage
      run: mvn jacoco:report -DskipTests=true

    - name: Display test coverage
      run: mvn jacoco:report
